config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :users
  as :user do
    get 'signin', to: 'devise/sessions#new'
    delete 'signout', to: 'devise/sessions#destroy'
    get 'signup', to: 'devise/registrations#new'
  end
  
  get 'feed', to: 'feed#show'
  resources :users, only: :show, param: :username do
    member do
      post 'follow', to: 'follows#create'
      delete 'unfollow', to: 'follows#destroy'
    end
  end
  resources :items
  resources :tweets

  root 'pages#home'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get '*path', to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/admin_authorization.rb
class AdminAuthorization < ActiveAdmin::AuthorizationAdapter
  def authorized?(action, subject = nil)
    user && user.admin?
  end
end

app/models/follow.rb
class Follow < ApplicationRecord

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" and "follower" interface
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user

  validates :user, presence: true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user

  validates :user, presence: true
  validates :content, presence: true, length: { maximum: 140 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :tweets
  has_many :items

  validates :username, presence: true, length: { minimum: 6 }
  validates :name, presence: true

  acts_as_followable
  acts_as_follower
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  add_flash_types :danger, :info, :warning, :success
  
  def access_denied(exception)
    redirect_to root_path, alert: exception.message
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name])
  end

end

app/controllers/feed_controller.rb
class FeedController < ApplicationController
  before_action :authenticate_user!

  def show
      @tweets = Tweet.where(user: current_user.all_following)
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_action :authenticate_user!

  def create
    user = User.find_by(username: params[:username])
    if current_user.following?(user)
      redirect_to user_path(user.username), notice: "You are already following #{user.username}"
    else
      Follow.create(followable: user, follower: current_user)
      redirect_to user_path(user.username), notice: "Successfully followed user"
    end
  end

  def destroy
    user = User.find_by(username: params[:username])
    Follow.find_by(followable: user, follower: current_user).destroy
    redirect_to user_path(user.username), notice: "Successfully unfollowed user"
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  # GET /items
  def index
    @items = Item.all
  end

  # GET /items/1
  def show
    @item = Item.find(params[:id])
  end

  # GET /items/new
  def new
    @item = current_user.items.new
  end

  # GET /items/1/edit
  def edit
    @item = current_user.items.find(params[:id])
  end

  # POST /items
  def create
    @item = current_user.items.new(item_params)


      if @item.save
        redirect_to @item, notice: 'Item was successfully created.'
      else
        render :new
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    @item = current_user.items.find(params[:id])
      if @item.update(item_params)
        redirect_to @item, notice: 'Item was successfully updated.'
      else
        render :edit
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = Item.find(params[:id])
    @item.destroy
      redirect_to items_url, notice: 'Item was successfully destroyed.'
  end

  private


    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :url, :text)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  # GET /tweets
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  def show
    @tweet = Tweet.find_by(id: params[:id])
    redirect_to root_path, :warning => 'Tweet not found' unless @tweet
  end

  # GET /tweets/new
  def new
    @tweet = current_user.tweets.new
  end

  # GET /tweets/1/edit
  def edit
    @tweet = current_user.tweets.find_by(id: params[:id])
    redirect_to root_path, :warning => 'You are not authorized to edit this tweet' unless @tweet
  end

  # POST /tweets
  def create
    @tweet = current_user.tweets.new(tweet_params)
    if @tweet.save
      redirect_to @tweet, notice: 'Tweet was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /tweets/1
  def update
    @tweet = current_user.tweets.find_by(id: params[:id])
    redirect_to root_path, :notice => 'You are not authorized to update this tweet' unless @tweet
    if @tweet.update(tweet_params)
      redirect_to @tweet, notice: 'Tweet was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /tweets/1
  def destroy
    @tweet = current_user.tweets.find(params[:id])
    @tweet.destroy
    redirect_to tweets_url, notice: 'Tweet was successfully destroyed.'
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by(username: params[:username])
    @tweets = @user.tweets
    redirect_to(root_path, :warning => 'User not found') unless @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/feed/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <div class="card card-block">
        <h4 class="card-title">Your Account</h4>
        <p class="card-text"><%= link_to current_user.username,
        user_path(current_user.username) %></p>
      </div>
    </div>

    <div class="col-md-8">
      <% if user_signed_in? %>
        <%= link_to 'New Tweet', new_tweet_path, class: "btn btn-primary" %>
      <% end %>
      <div class="list-group">

          <% @tweets.each do |tweet| %>
            <%= link_to tweet, class: "list-group-item list-group-item-action" do %>
              <h5 class="list-group-item-heading"><%= tweet.user.username %></h5>
              <p class="list-group-item-text"><%= tweet.content %></p>

              <% if tweet.user == current_user %>
                <%= link_to 'Edit', edit_tweet_path(tweet) %>
                <%= link_to 'Delete',  tweet, method: :delete,
                  data: {  confirm: 'Delete this tweet?', commit: 'Delete' }, title: ' ' %>
                <% end %>
            <% end %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>

app/views/items/_form.html.erb
<%= form_for(item) do |f| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= f.label :url %>
    <%= f.text_field :url, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= f.label :text %>
    <%= f.text_area :text, class: "form-control"  %>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/items/edit.html.erb
<div class="container">
  <h1>Editing Item</h1>

  <%= render 'form', item: @item %>

  <%= link_to 'Show', @item %> |
  <%= link_to 'Back', items_path %>
</div>

app/views/items/index.html.erb
<div class="container">

  <h1>Items</h1>

  <table>
    <thead>
      <tr>
        <th>User</th>
        <th>Title</th>
        <th>Url</th>
        <th>Text</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @items.each do |item| %>
        <tr>
          <td><%= item.user.username %></td>
          <td><%= item.title %></td>
          <td><%= item.url %></td>
          <td><%= item.text %></td>
          <td><%= link_to 'Show', item %></td>
          <% if item.user == current_user %>
            <td><%= link_to 'Edit', edit_item_path(item) %></td>
            <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Item', new_item_path %>
</div>

app/views/items/new.html.erb
<div class="container">
  <h1>New Item</h1>

  <%= render 'form', item: @item %>

  <%= link_to 'Back', items_path %>
</div>

app/views/items/show.html.erb
<div class="container">

  <p>
    <strong>User:</strong>
    <%= @item.user.username %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= @item.title %>
  </p>

  <p>
    <strong>Url:</strong>
    <%= @item.url %>
  </p>

  <% if @item.text? %>
    <p>
      <strong>Text:</strong>
      <%= @item.text %>
    </p>
  <% end %>
  <% if @item.user == current_user %>
    <%= link_to 'Edit', edit_item_path(@item) %> |
  <% end %>
    <%= link_to 'Back', items_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>One Month Rails Project</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <!-- Navigation Bar -->
    <nav class="navbar navbar-dark bg-inverse">
      <div class="container">
        <%= link_to "One Month Rails", root_path, class: "navbar-brand" %>
        <ul class="nav navbar-nav">
          <li class="nav-item"><%= link_to "Home", root_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "About", about_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "Contact", "#", class: "nav-link" %></li>
          <% if user_signed_in? %>
            <li class="nav-item pull-md-right"><%= link_to "Log Out", signout_path, method: :delete, class: "nav-link" %></li>
          <% else %>
            <li class="nav-item pull-md-right"><%= link_to "Log In", signin_path, class: "nav-link" %></li>
            <li class="nav-item pull-md-right "><%= link_to "Sign Up", signup_path, class: "btn btn-primary" %></li>
          <% end %>
        </ul>
      </div>
    </nav>

    <!-- Flash Message -->
    <% flash.each do |name, message| %>
      <% if name != 'warning' or name != 'danger' or name != 'success' or name != 'notice'%>
        <%= content_tag(:div, message, class: "alert alert-info") %>
      <% else %>
        <div class='alert alert-<%= name %>'>
          <%= message %>
        </div>
      <% end %>
    <% end %>

    <!-- Page Content -->
    <%= yield %>

    <!-- Footer -->
    <footer class="small text-muted">
      <div class="container">
        <hr>
        <center>
          <p>© 2016 One Month</p>
        </center>
      </div>
    </footer>

  </body>
</html>

app/views/pages/about.html.erb
<div class="jumbotron">
    <div class="container">
        <h1>About us</h1>
        <p>This is the sample project I built for <a href="https://onemonthrails.com">One Month Rails</a>.</p>
    </div>
</div>

app/views/pages/contact.html.erb
<div class="text-center">
  <h1>Contact Nelson</h1>
  <p><span class="glyphicon glyphicon-globe">&nbsp</span><a href="https://nelsonlho.github.io/">https://nelsonlho.github.io/</a></p>
  <p><span class="glyphicon glyphicon-envelope"/>&nbsp</span>nelsonlho@gmail.com
  <p><span class="glyphicon glyphicon-phone">&nbsp</span>415.335.1936</p>
</div>

app/views/pages/home.html.erb
<% if user_signed_in? %>

  <div class="jumbotron jumbotron-home">
      <div class="container">
          <h1> Welcome back </h1>
      </div>
  </div>

<% else %>
  <div class="jumbotron jumbotron-home">
      <div class="container">
          <h1>Welcome to my website!</h1>
          <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
          <%= link_to "Learn more »", "#", class: "btn btn-primary btn-lg" %>
      </div>
  </div>
  <div class="container">
      <div class="row">
          <div class="col-md-4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><%= link_to "View details", "#", class: "btn btn-secondary" %></p>
          </div>
          <div class="col-md-4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><%= link_to "View details", "#", class: "btn btn-secondary" %></p>
          </div>
          <div class="col-md-4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><%= link_to "View details", "#", class: "btn btn-secondary" %></p>
          </div>
      </div>
  </div>
<% end %>

app/views/tweets/_form.html.erb
<%= form_for(tweet) do |f| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, class: "form-control"  %>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<div class="container">
  <h1>Editing Tweet</h1>

  <%= render 'form', tweet: @tweet %>

  <%= link_to 'Show', @tweet %> |
  <%= link_to 'Back', tweets_path %>
</div>

app/views/tweets/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <div class="card card-block">
        <% if user_signed_in? %>
          <h4 class="card-title">Your Account</h4>
          <p class="card-text"><%= link_to current_user.username,
          user_path(current_user.username) %></p>
        <% else %>
          <p class="card-text"><%= link_to "Sign up now!", signup_path  %>
        <% end %>
      </div>
    </div>

    <div class="col-md-8">
      <% if user_signed_in? %>
        <%= link_to 'New Tweet', new_tweet_path, class: "btn btn-primary" %>
      <% end %>
      <div class="list-group">

          <% @tweets.each do |tweet| %>
            <%= link_to tweet, class: "list-group-item list-group-item-action" do %>
              <h5 class="list-group-item-heading"><%= tweet.user.username %></h5>
              <p class="list-group-item-text"><%= tweet.content %></p>

              <% if tweet.user == current_user %>
                <%= link_to 'Edit', edit_tweet_path(tweet) %>
                <%= link_to 'Delete',  tweet, method: :delete,
                  data: {  confirm: 'Delete this tweet?', commit: 'Delete' }, title: ' ' %>
                <% end %>
            <% end %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>

app/views/tweets/new.html.erb
<div class="container">
  <h1>New Tweet</h1>

  <%= render 'form', tweet: @tweet %>

  <%= link_to 'Back', tweets_path %>
</div>

app/views/tweets/show.html.erb
<div class="container">
  <div class="row">
    <div class="offset-md-2 col-md-8">
      <div class="card card-block">
        <h4 class="card-title"><%= link_to @tweet.user.username,
        user_path(@tweet.user.username) %></h4>
        <p class="card-text"><%= @tweet.content %></p>
        <% if @tweet.user == current_user %>
          <%= link_to 'Edit', edit_tweet_path(@tweet), class: "class-link" %> |
          <%= link_to 'Delete', @tweet, method: :delete, class: "class-link" %> |
        <% end %>
        <%= link_to 'Back', tweets_path, class: "class-link" %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <div class="card card-block">
        <h4 class="card-title"><%= link_to @user.username,
        user_path(@user.username) %></h4>
        <p class="card-text"><%= @user.name %></p>
        <% if user_signed_in? %>
          <% if @user != current_user%>
            <% if current_user.following?(@user) %>
              <p class="card-text"><%= link_to "Unfollow", unfollow_user_path(@user.username),
              method: :delete %></p>
            <% else %>
              <p class="card-text"><%= link_to "Follow", follow_user_path(@user.username),
              method: :post %></p>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>

    <div class="col-md-8">
      <div class="list-group">

          <% @tweets.each do |tweet| %>
            <%= link_to tweet, class: "list-group-item list-group-item-action" do %>
              <h5 class="list-group-item-heading"><%= tweet.user.username %></h5>
              <p class="list-group-item-text"><%= tweet.content %></p>

              <% if tweet.user == current_user %>
                <%= link_to 'Edit', edit_tweet_path(tweet) %>
                <%= link_to 'Delete',  tweet, method: :delete,
                  data: {  confirm: 'Delete this tweet?', commit: 'Delete' }, title: ' ' %>
                <% end %>
            <% end %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>